### ISSUE TITLE
Some ESRI:MapServers are not correctly harvested

### ISSUE THREAD

**Issue by ingenieroariel** [cga-harvard/HHypermap#189]
Let's check them off from the list as we make them work:

 - [ ] https://services.arcgisonline.com/arcgis/rest/services/NGS_Topo_US_2D/MapServer

**Comment by ingenieroariel** [comment]
From Erick at Boundless:

There's 2 parts to this issue.

Issue #1.
When adding https://services.arcgisonline.com/arcgis/rest/services/NGS_Topo_US_2D/MapServer as an Endpoint, I see the following error in the Celery logs:

[2016-08-31 10:49:05,606: ERROR/Worker-4] local variable 'service_to_process' referenced before assignment
Traceback (most recent call last):
File "/opt/boundless/exchange/.venv/lib/python2.7/site-packages/hypermap/aggregator/utils.py", line 308, in create_services_from_endpoint
service_to_process = get_single_service(esri, url, endpoint)
File "/opt/boundless/exchange/.venv/lib/python2.7/site-packages/hypermap/aggregator/utils.py", line 344, in get_single_service
return service_to_process
UnboundLocalError: local variable 'service_to_process' referenced before assignment
[2016-08-31 10:49:05,628: INFO/MainProcess] Task hypermap.aggregator.tasks.update_endpoint[00027c4a-aa00-4787-911b-2d050f7b4907] succeeded in 1.523003477s: None
Issue #2
After modifying utils.py above to initialize service_to_process, Registry is still unable to discover layers/servcies from:

https://services.arcgisonline.com/arcgis/rest/services/NGS_Topo_US_2D/MapServer

[2016-08-31 11:11:51,782: INFO/MainProcess] Received task: hypermap.aggregator.tasks.update_endpoint[1da46561-2ea3-467b-bb7d-9ad344f19458]
[2016-08-31 11:11:52,063: INFO/Worker-3] Starting new HTTPS connection (1): services.arcgisonline.com
[2016-08-31 11:11:52,373: INFO/Worker-3] Starting new HTTPS connection (1): services.arcgisonline.com
[2016-08-31 11:11:52,642: INFO/Worker-3] Starting new HTTPS connection (1): services.arcgisonline.com
[2016-08-31 11:11:52,927: INFO/Worker-3] Starting new HTTPS connection (1): services.arcgisonline.com
[2016-08-31 11:11:53,695: INFO/MainProcess] Task hypermap.aggregator.tasks.update_endpoint[1da46561-2ea3-467b-bb7d-9ad344f19458] succeeded in 1.910557994s: None

**Comment by ingenieroariel** [comment]
![screen shot 2016-09-06 at 11 23 43 am](https://cloud.githubusercontent.com/assets/54999/18281934/7617b834-7424-11e6-945a-68bb78b8db82.png)
![screen shot 2016-09-06 at 11 24 32 am](https://cloud.githubusercontent.com/assets/54999/18281942/85b118b2-7424-11e6-86e1-0abd46cf04f3.png)

**Comment by ingenieroariel** [comment]
![screen shot 2016-09-06 at 11 36 29 am](https://cloud.githubusercontent.com/assets/54999/18282308/3104ff98-7426-11e6-9f62-d658c8c5a3ef.png)

**Comment by ingenieroariel** [comment]
Fixed. Thanks @JorgeMartinezG
