### ISSUE TITLE
Move to elasticsearch with heatmap support

### ISSUE THREAD

**Issue by JorgeMartinezG** [cga-harvard/HHypermap#230]
- [x] Test heatmap works via api
 - [x] Test heatmap in OL3
 - [ ] Fix tests

**Comment by ingenieroariel** [comment]
@JorgeMartinezG to fix tests you will first have to uncomment them. I believe @panchicore commented them all I but I am not sure why.

**Comment by JorgeMartinezG** [comment]
Travis tests won't pass because this version of elasticsearch has permission issues when the docker image is run on Linux environments. I tested in Ubuntu 16.04 with this ouput.

```
elasticsearch_1     | ERROR: bootstrap checks failed
elasticsearch_1     | max virtual memory areas vm.max_map_count [65530] likely too low, increase to at least [262144]
elasticsearch_1     | [2016-10-12T16:22:18,306][INFO ][o.e.n.Node               ] [h5-37br] stopping ...
elasticsearch_1     | 2016-10-12 16:22:18,315 pool-1-thread-1 ERROR Unable to unregister MBeans java.security.AccessControlException: access denied ("javax.management.MBeanServerPermission" "createMBeanServer")
elasticsearch_1     | 	at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472)
elasticsearch_1     | 	at java.security.AccessController.checkPermission(AccessController.java:884)
elasticsearch_1     | 	at java.lang.SecurityManager.checkPermission(SecurityManager.java:549)
elasticsearch_1     | 	at java.lang.management.ManagementFactory.getPlatformMBeanServer(ManagementFactory.java:465)
elasticsearch_1     | 	at org.apache.logging.log4j.core.jmx.Server.unregisterLoggerContext(Server.java:246)
elasticsearch_1     | 	at org.apache.logging.log4j.core.LoggerContext.stop(LoggerContext.java:300)
elasticsearch_1     | 	at org.apache.logging.log4j.core.LoggerContext$1.run(LoggerContext.java:265)
elasticsearch_1     | 	at org.apache.logging.log4j.core.util.DefaultShutdownCallbackRegistry$RegisteredCancellable.run(DefaultShutdownCallbackRegistry.java:102)
elasticsearch_1     | 	at org.apache.logging.log4j.core.util.DefaultShutdownCallbackRegistry.run(DefaultShutdownCallbackRegistry.java:72)
elasticsearch_1     | 	at java.lang.Thread.run(Thread.java:745)
elasticsearch_1     | 
elasticsearch_1     | 
elasticsearch_1     | Exception: java.security.AccessControlException thrown from the UncaughtExceptionHandler in thread "Thread-2"
```

Checking in the forums....they recommend to grant permissions. Any thoughts? @ingenieroariel @sstults

**Comment by ingenieroariel** [comment]
Can you run the tests with the official 5.0.0 image [0] and then use that Dockerfile as the basis for this one? [1]

[0] https://github.com/docker-library/elasticsearch/blob/master/5.0/Dockerfile
[1] Switch to the following image: `elasticsearch:5.0.0-rc1` from https://hub.docker.com/_/elasticsearch/

**Comment by JorgeMartinezG** [comment]
It's a good idea. However, that elasticsearch version won't have the gridlevel support, because the current dockerfile pulls from this repo:

https://github.com/sstults/elasticsearch/

**Comment by ingenieroariel** [comment]
Right - what I mean is building that elastic search exactly like the official one. Or using the official one and then just replacing the artifacts with ones compiled from the branch

**Comment by JorgeMartinezG** [comment]
Virtual memory map area in Linux, comes with a small value. This causes elasticsearch to stop execution on its container, making travis fail. Fix is already sent in PR with tests passed

https://github.com/cga-harvard/HHypermap/pull/231

**Comment by JorgeMartinezG** [comment]
Heatmap test is failing executing one assertion. The test was created to assert if a returning value is None. However, in solr, the returned value is an empty list. For elasticsearch, is a list of empty lists.

https://github.com/cga-harvard/HHypermap/blob/issue_230/hypermap/search_api/tests.py#L346

**Comment by danielguerra69** [comment]
ES_JAVA_OPTS="-Xms512m -Xmx512m" ./elasticsearch/bin Solves the problem for me

**Comment by capooti** [comment]
@JorgeMartinezG @ingenieroariel can this be closed?
