### ISSUE TITLE
Tests fail: list index out of range

### ISSUE THREAD

**Issue by capooti** [cga-harvard/HHypermap#271]
======================================================================
ERROR: test_layer_fields (hypermap.aggregator.tests.test_metadata.TestMetadata)
test Layer metadata fields
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/src/app/hypermap/aggregator/tests/test_metadata.py", line 97, in test_layer_fields
    layer = Layer.objects.filter(type='OGC:WMS').all()[0]
  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 201, in __getitem__
    return list(qs)[0]
IndexError: list index out of range

**Comment by capooti** [comment]
Looks like the mocks are not working. I will take a look.
